language: ruby
rvm:
  - 2.6
cache: bundler
bundler_args: --without production
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
